# Generated by Django 4.2.3 on 2023-07-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Poject_ideass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(choices=[(0, 'mini project'), (1, 'main project'), (2, 'live project')])),
                ('Description', models.TextField()),
                ('project_title', models.CharField(max_length=300)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.course')),
                ('Technology', models.ManyToManyField(blank=True, to='ideas.technology')),
            ],
        ),
    ]
