# Generated by Django 4.2.3 on 2023-07-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject_ideass',
            new_name='Project_ideass',
        ),
    ]
